### ISSUE TITLE
Add right joystick to leftPower and rightPower

### ISSUE THREAD

**Issue by npant03** [npant03/InfiniteRecharge2020#19]
In ArcadeDrive, add the 0.5 * y-values of the right joystick to the left and right powers being given to the robot. This will allow a full-speed mode when both joysticks are used, as well as more fine-tuned control on just the right stick.

**Comment by npant03** [comment]
Written in week1-comp-manual, needs to be tested

**Comment by nehaxpant** [comment]
written in week1-manual, need to test

**Comment by nehaxpant** [comment]
need to invert @H3nryM
